cache: bundler
language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-9
  - rbx
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
